version: "3"
services:
  web:
    build: .
    container_name: web
    hostname: web
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    command: bash -c 'gunicorn -c conf/gunicorn.py "run:app"'
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db